### ISSUE TITLE
bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by Hoomanmsh** [ali77gh/shecan-cli#1]
hi,

I tried to install and use this cli but, after installation , I got this error when use `shecan-cli enable`

`bash: /usr/bin/shecan-cli: /bin/python3: bad interpreter: No such file or directory`

**Comment by ali77gh** [comment]
Hi hooman.🖐️
Run this command and share result:
# which python3

This will show your python path.
First shere result with me then open /usr/bin/shecan-cli with your favorite text editor.

Try to replace your python path in first line.

BTW I'm trying to fix this in next commit.

**Comment by ali77gh** [comment]
Hello again.
Try to use [this](https://github.com/ali77gh/shecan-cli/blob/fixshebang/shecan.py) file. 
copy the content of file to /usr/bin/shecan-cli
If it works let me know then i will merge branch with master.
Thanks for creating whits issue.

**Comment by Hoomanmsh** [comment]
Dear @ali77gh,
your solution worked for me , I changed the "/bin/python3" with "/usr/bin/python3" and the cli fixed.

thanks for your help.

**Comment by Hoomanmsh** [comment]
@ali77gh for your second comment , 
I was checked this new file and worked for me.
thanks
